version: 2

sources:
    - name: xw_shop
      description: This is a replica of the Postgres database used by our app
      database: raw
      schema: xw_shop
      tables:
          - name: customers
            description: One record per customer.
          - name: orders
            description: One record per order. Includes cancelled and deleted orders.
          # - name: payments
          #   description: One record per payment. Stripe payment.
    - name: gp_tran
      description: This is a replica of the Postgres database used by our app
      database: raw
      schema: gp_tran
      tables:
          - name: payment
            description: One record per payment. Stripe payment.
